#include "Avionics.h"


/*
 * Function: debugState
 * -------------------
 * This function provides debuging information.
 */
bool Avionics::debugState() {
  printState();
  //if(data.DEBUG_STATE) printState();
  return true;
}

/*
 * Function: alert
 * -------------------
 * This function alerts important information whenever a specific event occurs.
 */
void Avionics::alert(const char* debug, bool fatal) {
  if(!data.DEBUG_STATE) return;
  Serial.print(millis());
  Serial.print(',');
  if(fatal) Serial.print("FATAL ERROR!!!!!!!!!!: ");
  else Serial.print("Alert: ");
  Serial.print(debug);
  Serial.print("...\n");
}

/*
 * Function: printState
 * -------------------
 * This function prints the current avionics state.
 */
void Avionics::printState() {
  //if (data.LOOP_NUMBER % 500 != 0) return;
  // Serial.print("CURRENT MOTORS: ");
  //   Serial.print(data.CURRENT_MOTORS);
  //   Serial.print(" ");
  //     Serial.print(data.CURRENT_TOTAL);
  //     Serial.print(" ");
  //       Serial.print(data.CURRENT_RB);
  //     Serial.print(" ");
  //       Serial.print(data.CURRENT_PAYLOAD);
  //     Serial.print(" ");
  //     //Serial.print(data.CURRENT_MOTOR_BALLAST_AVG);
  //     Serial.println();

	Serial.println();
	Serial.println();

  Serial.print(" RAW_PRESSURE_1:");
  Serial.print(data.RAW_PRESSURE_1);
  Serial.print(',');
  Serial.print(" RAW_PRESSURE_2:");
  Serial.print(data.RAW_PRESSURE_2);
  Serial.print(',');
  Serial.print(" RAW_PRESSURE_3:");
  Serial.print(data.RAW_PRESSURE_3);
  Serial.print(',');
  Serial.print(" RAW_PRESSURE_4:");
  Serial.print(data.RAW_PRESSURE_4);
	Serial.println();
  Serial.println(sensors.bmp1.readPressure());
  Serial.println(sensors.bmp2.readPressure());
Serial.println();
Serial.print(sensors.getVoltageSuperCap());
Serial.println(" Volts.");
Serial.println();
	return;
  Serial.print("Altitude: ");
  Serial.println(data.ALTITUDE_BAROMETER);
  Serial.print("LOOP_TIME: ");
  Serial.println(filter.loop_time.avg);
  return;
  Serial.print("!!!!!!manual mode ");
  Serial.println(data.MANUAL_MODE);
  //return;
  Serial.print("Altitude: ");
  Serial.println(data.ALTITUDE_BAROMETER);
  Serial.print("Primary voltage: ");
  Serial.println(data.VOLTAGE_PRIMARY);
  Serial.print("Primary voltage min: ");
  Serial.println(filter.voltage_primary.min);
  Serial.print("Supercap avg voltage: ");
  Serial.println(data.VOLTAGE_SUPERCAP_AVG);
  Serial.print("Supercap min voltage: ");
  Serial.println(data.VOLTAGE_SUPERCAP_MIN);
  // Serial.print("System current: ");
  // Serial.println(data.CURRENT_TOTAL);
  Serial.print("System current: ");
  Serial.println(data.CURRENT_TOTAL);
  Serial.print("Payload current: ");
  Serial.println(data.CURRENT_PAYLOAD);
  Serial.print("Motor current: ");
  Serial.println(data.CURRENT_MOTORS);
  Serial.print("RB current: ");
  Serial.println(data.CURRENT_RB);
  Serial.print("Overpressure: ");
  Serial.println(data.OVERPRESSURE_FILT);
  Serial.print("Overpressure vref: ");
  Serial.println(data.OVERPRESSURE_VREF_FILT);
  //return;
  // Serial.print("MANUAL_MODE: ");
  // Serial.println(data.MANUAL_MODE);

  // Serial.print(" RAW_TEMP_1:");
  // Serial.print(data.RAW_TEMP_1);
  // Serial.print(',');
  // Serial.print(" RAW_TEMP_2:");
  // Serial.print(data.RAW_TEMP_2);
  // Serial.print(',');
  // Serial.print(" RAW_TEMP_3:");
  // Serial.print(data.RAW_TEMP_3);
  // Serial.print(',');
  // Serial.print(" RAW_TEMP_4:");
  // Serial.print(data.RAW_TEMP_4);
  // Serial.print(',');
  Serial.print("RAW_PRESSURE_1: ");
  Serial.println(data.RAW_PRESSURE_1);
  Serial.print(',');
  Serial.print("RAW_PRESSURE_2: ");
  Serial.println(data.RAW_PRESSURE_2);
  Serial.print(',');
  Serial.print("RAW_PRESSURE_3: ");
  Serial.println(data.RAW_PRESSURE_3);
  Serial.print(',');
  Serial.print("RAW_PRESSURE_4: ");
  Serial.println(data.RAW_PRESSURE_4);
  Serial.println();
  //return;

  Serial.print("MANUAL_MODE: ");
  Serial.println(data.MANUAL_MODE);
  Serial.print("CONTROLLER: ");
  Serial.println(data.CURRENT_CONTROLLER_INDEX);
  Serial.print("SPAG_EFFORT: ");
  Serial.println(data.SPAG_STATE.effort*1000);
  Serial.print("SPAG2_EFFORT: ");
  Serial.println(data.SPAG2_STATE.effort*1000);
  Serial.print("LAS_EFFORT: ");
  Serial.println(data.LAS_STATE.effort*1000);
  Serial.print("VALVE_INCENTIVE_LEGACY: ");
  Serial.println(data.VALVE_INCENTIVE);
  Serial.print("BALLAST_INCENTIVE_LEGACY: ");
  Serial.println(data.BALLAST_INCENTIVE);
  Serial.print("VALVE QUEUE: ");
  Serial.println(data.VALVE_QUEUE);
  Serial.print("BALLAST QUEUE: ");
  Serial.println(data.BALLAST_QUEUE);
  Serial.print("ACTION: ");
  Serial.println(data.ACTION);

  Serial.println("action crap");
  for (int kk = 0; kk < 4; kk++ ) {
    Serial.print(data.ACTION_TIME_TOTALS[2*kk]);
    Serial.print(" ");
      Serial.print(data.ACTION_TIME_TOTALS[2*kk+1]);
      Serial.println();
  }
      Serial.println();
  Serial.println();
  Serial.print("TIME:");
  Serial.print(data.TIME);
  Serial.print(',');
  Serial.print(" LAT_GPS:");
  Serial.print(data.LAT_GPS, 4);
  Serial.print(',');
  Serial.print(" LONG_GPS:");
  Serial.print(data.LONG_GPS, 4);
  Serial.print(',');
  Serial.print(" ALTITUDE_BAROMETER:");
  Serial.print(data.ALTITUDE_BAROMETER);
  Serial.print(',');
  Serial.print(" ALTITUDE_GPS:");
  Serial.print(data.ALTITUDE_GPS);
  Serial.print(',');
  Serial.print(" ASCENT_RATE:");
  Serial.print(data.ASCENT_RATE);
  Serial.print(',');
  Serial.print(" ACTION:");
  Serial.print(data.ACTION);
  Serial.print(',');
  Serial.print(" VALVE_STATE:");
  Serial.print(data.VALVE_STATE);
  Serial.print(',');
  Serial.print(" BALLAST_STATE:");
  Serial.print(data.BALLAST_STATE);
  Serial.print(',');
  Serial.print(" VALVE_QUEUE:");
  Serial.print(data.VALVE_QUEUE);
  Serial.print(',');
  Serial.print(" BALLAST_QUEUE:");
  Serial.print(data.BALLAST_QUEUE);
  Serial.print(',');
  Serial.print(" VALVE_TIME_TOTAL:");
  Serial.print(data.VALVE_TIME_TOTAL);
  Serial.print(',');
  Serial.print(" BALLAST_TIME_TOTAL:");
  Serial.print(data.BALLAST_TIME_TOTAL);
  Serial.print(',');
  Serial.print(" VALVE_NUM_ACTIONS:");
  Serial.print(data.VALVE_NUM_ACTIONS);
  Serial.print(',');
  Serial.print(" BALLAST_NUM_ACTIONS:");
  Serial.print(data.BALLAST_NUM_ACTIONS);
  Serial.print(',');
  Serial.print(" VALVE_NUM_ATTEMPTS:");
  Serial.print(data.VALVE_NUM_ATTEMPTS);
  Serial.print(',');
  Serial.print(" BALLAST_NUM_ATTEMPTS:");
  Serial.print(data.BALLAST_NUM_ATTEMPTS);
  Serial.print(',');
  Serial.print(" BALLAST_NUM_OVERCURRENTS:");
  Serial.print(data.BALLAST_NUM_OVERCURRENTS);
  Serial.print(',');
  Serial.print(" CUTDOWN_STATE:");
  Serial.print(data.CUTDOWN_STATE);
  Serial.print(',');
  Serial.print(" MAX_CURRENT_CHARGING_LIMIT:");
  Serial.print(data.MAX_CURRENT_CHARGING_LIMIT);
  Serial.print(',');
  Serial.print(" SYSTEM_POWER_STATE:");
  Serial.print(data.SYSTEM_POWER_STATE);
  Serial.print(',');
  Serial.print(" TEMP_INT:");
  Serial.print(data.TEMP_INT);
  Serial.print(',');
  Serial.print(" JOULES_TOTAL:");
  Serial.print(data.JOULES_TOTAL);
  Serial.print(',');
  Serial.print(" VOLTAGE_PRIMARY:");
  Serial.print(data.VOLTAGE_PRIMARY);
  Serial.print( ',');
  Serial.print(" VOLTAGE_SUPERCAP_AVG:");
  Serial.print(data.VOLTAGE_SUPERCAP_AVG);
  Serial.print(',');
  Serial.print(" CURRENT_TOTAL_AVG:");
  Serial.print(filter.current_total.avg);
  Serial.print(',');
  Serial.print(" CURRENT_TOTAL_MIN:");
  Serial.print(filter.current_total.min);
  Serial.print(',');
  Serial.print(" CURRENT_TOTAL_MAX:");
  Serial.print(filter.current_total.max);
  Serial.print(',');
  Serial.print(" CURRENT_RB_AVG:");
  Serial.print(filter.current_rb.avg);
  Serial.print(',');
  Serial.print(" CURRENT_RB_MAX:");
  Serial.print(filter.current_rb.max);
  Serial.print(',');
  return;
  Serial.print(',');
  Serial.print(" TEMP_EXT:");
  Serial.print(data.TEMP_EXT);
  Serial.print(',');
  Serial.print(" LOOP_TIME_MAX:");
  Serial.print(data.LOOP_TIME_MAX);
  Serial.print(',');
  Serial.print(" RB_SENT_COMMS:");
  Serial.print(data.RB_SENT_COMMS);
  Serial.print(',');
  Serial.print(" RESISTOR_MODE:");
  Serial.print(data.RESISTOR_MODE);
  Serial.print(',');
  Serial.print(" MANUAL_MODE:");
  Serial.print(data.MANUAL_MODE);
  Serial.print(',');
  Serial.print(" REPORT_MODE:");
  Serial.print(data.REPORT_MODE);
  Serial.print(',');
  Serial.print(" SHOULD_REPORT:");
  Serial.print(data.SHOULD_REPORT);
  Serial.print(',');
  Serial.print(" POWER_STATE_LED:");
  Serial.print(data.POWER_STATE_LED);
  Serial.print(',');
  Serial.print(" POWER_STATE_RB:");
  Serial.print(data.POWER_STATE_RB);
  Serial.print(',');
  Serial.print(" POWER_STATE_GPS:");
  Serial.print(data.POWER_STATE_GPS);
  Serial.print(',');
  Serial.print(" POWER_STATE_PAYLOAD:");
  Serial.print(data.POWER_STATE_PAYLOAD);
  Serial.print(',');
  Serial.print(" NUM_SATS_GPS:");
  Serial.print(data.NUM_SATS_GPS);
  Serial.print(',');
  Serial.print(" SPEED_GPS:");
  Serial.print(data.SPEED_GPS);
  Serial.print(',');
  Serial.print(" HEADING_GPS:");
  Serial.print(data.HEADING_GPS);
  Serial.print(',');
  Serial.print(" INCENTIVE_NOISE:");
  Serial.print(data.INCENTIVE_NOISE);
  Serial.print(',');
  Serial.print(" VALVE_ALT_LAST:");
  Serial.print(data.VALVE_ALT_LAST);
  Serial.print(',');
  Serial.print(" BALLAST_ALT_LAST:");
  Serial.print(data.BALLAST_ALT_LAST);
  Serial.print(',');
  // START OF CONTROLLER SWITCHING ADDITION
  Serial.print(" CURRENT_CONTROLLER_INDEX:");
  Serial.print(data.CURRENT_CONTROLLER_INDEX);
  Serial.print(',');
  Serial.print(',');
 // END OF CONTROLLER SWITCHING ADDITION
  Serial.print(" DEBUG_STATE:");
  Serial.print(data.DEBUG_STATE);
  Serial.print(',');
  Serial.print(" FORCE_VALVE:");
  Serial.print(data.FORCE_VALVE);
  Serial.print(',');
  Serial.print(" FORCE_BALLAST:");
  Serial.print(data.FORCE_BALLAST);
  Serial.print(',');
  Serial.print(" BMP_1_ENABLE:");
  Serial.print(data.BMP_ENABLE[0]);
  Serial.print(',');
  Serial.print(" BMP_2_ENABLE:");
  Serial.print(data.BMP_ENABLE[1]);
  Serial.print(',');
  Serial.print(" BMP_3_ENABLE:");
  Serial.print(data.BMP_ENABLE[2]);
  Serial.print(',');
  Serial.print(" BMP_4_ENABLE:");
  Serial.print(data.BMP_ENABLE[3]);
  Serial.print(',');
  Serial.print(" BMP_1_REJECTIONS:");
  Serial.print(data.BMP_REJECTIONS[0]);
  Serial.print(',');
  Serial.print(" BMP_2_REJECTIONS:");
  Serial.print(data.BMP_REJECTIONS[1]);
  Serial.print(',');
  Serial.print(" BMP_3_REJECTIONS:");
  Serial.print(data.BMP_REJECTIONS[2]);
  Serial.print(',');
  Serial.print(" BMP_4_REJECTIONS:");
  Serial.print(data.BMP_REJECTIONS[3]);
  Serial.print(',');
  Serial.print(" RB_INTERVAL:");
  Serial.print(data.RB_INTERVAL);
  Serial.print(',');
  Serial.print(" GPS_INTERVAL:");
  Serial.print(data.GPS_INTERVAL);
  Serial.print(',');
  Serial.print(" PRESS_BASELINE:");
  Serial.print(data.PRESS_BASELINE);
  Serial.print(',');
  Serial.print(" INCENTIVE_THRESHOLD:");
  Serial.print(data.INCENTIVE_THRESHOLD);
  Serial.print(',');
  Serial.print(" BALLAST_ARM_ALT:");
  Serial.print(data.BALLAST_ARM_ALT);
  Serial.print(',');
  Serial.print(" BALLAST_REVERSE_INTERVAL:");
  Serial.print(data.BALLAST_REVERSE_INTERVAL);
  Serial.print(',');
  Serial.print(" BALLAST_STALL_CURRENT:");
  Serial.print(data.BALLAST_STALL_CURRENT);
  Serial.print(',');
  Serial.print(" VALVE_MOTOR_SPEED_OPEN:");
  Serial.print(data.VALVE_MOTOR_SPEED_OPEN);
  Serial.print(',');
  Serial.print(" VALVE_MOTOR_SPEED_CLOSE:");
  Serial.print(data.VALVE_MOTOR_SPEED_CLOSE);
  Serial.print(',');
  Serial.print(" BALLAST_MOTOR_SPEED:");
  Serial.print(data.BALLAST_MOTOR_SPEED);
  Serial.print(',');
  Serial.print(" VALVE_OPENING_DURATION:");
  Serial.print(data.VALVE_OPENING_DURATION);
  Serial.print(',');
  Serial.print(" VALVE_CLOSING_DURATION:");
  Serial.print(data.VALVE_CLOSING_DURATION);
  Serial.print(',');
  Serial.print(" VALVE_SETPOINT:");
  Serial.print(data.VALVE_SETPOINT);
  Serial.print(',');
  Serial.print(" VALVE_VENT_DURATION:");
  Serial.print(data.VALVE_VENT_DURATION);
  Serial.print(',');
  Serial.print(" VALVE_FORCE_DURATION:");
  Serial.print(data.VALVE_FORCE_DURATION);
  Serial.print(',');
  Serial.print(" VALVE_VELOCITY_CONSTANT:");
  Serial.print(data.VALVE_VELOCITY_CONSTANT);
  Serial.print(',');
  Serial.print(" VALVE_ALTITUDE_DIFF_CONSTANT (1.0 / ):");
  Serial.print(1.0 / data.VALVE_ALTITUDE_DIFF_CONSTANT);
  Serial.print(',');
  Serial.print(" VALVE_LAST_ACTION_CONSTANT (1.0 / ):");
  Serial.print(1.0 / data.VALVE_LAST_ACTION_CONSTANT);
  Serial.print(',');
  Serial.print(" BALLAST_SETPOINT:");
  Serial.print(data.BALLAST_SETPOINT);
  Serial.print(',');
  Serial.print(" BALLAST_DROP_DURATION:");
  Serial.print(data.BALLAST_DROP_DURATION);
  Serial.print(',');
  Serial.print(" BALLAST_FORCE_DURATION:");
  Serial.print(data.BALLAST_FORCE_DURATION);
  Serial.print(',');
  Serial.print(" BALLAST_VELOCITY_CONSTANT:");
  Serial.print(data.BALLAST_VELOCITY_CONSTANT);
  Serial.print(',');
  Serial.print(" BALLAST_ALTITUDE_DIFF_CONSTANT (1.0 / ):");
  Serial.print(1.0 / data.BALLAST_ALTITUDE_DIFF_CONSTANT);
  Serial.print(',');
  Serial.print(" BALLAST_LAST_ACTION_CONSTANT (1.0 / ):");
  Serial.print(1.0 / data.BALLAST_LAST_ACTION_CONSTANT);
  Serial.print(',');
  Serial.print(" SETUP_STATE:");
  Serial.print(data.SETUP_STATE);
  Serial.print(',');
  Serial.print(" SHOULD_CUTDOWN:");
  Serial.print(data.SHOULD_CUTDOWN);
  Serial.print(',');
  Serial.print(" LOOP_TIME:");
  Serial.print(data.LOOP_TIME);
  Serial.print(',');
  Serial.print(" RAW_TEMP_1:");
  Serial.print(data.RAW_TEMP_1);
  Serial.print(',');
  Serial.print(" RAW_TEMP_2:");
  Serial.print(data.RAW_TEMP_2);
  Serial.print(',');
  Serial.print(" RAW_TEMP_3:");
  Serial.print(data.RAW_TEMP_3);
  Serial.print(',');
  Serial.print(" RAW_TEMP_4:");
  Serial.print(data.RAW_TEMP_4);
  Serial.print(',');
  Serial.print(" RAW_PRESSURE_1:");
  Serial.print(data.RAW_PRESSURE_1);
  Serial.print(',');
  Serial.print(" RAW_PRESSURE_2:");
  Serial.print(data.RAW_PRESSURE_2);
  Serial.print(',');
  Serial.print(" RAW_PRESSURE_3:");
  Serial.print(data.RAW_PRESSURE_3);
  Serial.print(',');
  Serial.print(" RAW_PRESSURE_4:");
  Serial.print(data.RAW_PRESSURE_4);
  Serial.print(',');
  Serial.print(" VOLTAGE_SUPERCAP:");
  Serial.print(data.VOLTAGE_SUPERCAP);
  Serial.print(',');
  Serial.print(" CURRENT_TOTAL:");
  Serial.print(data.CURRENT_TOTAL);
  Serial.print(',');
  Serial.print(" CURRENT_RB:");
  Serial.print(data.CURRENT_RB);
  Serial.print(',');
  Serial.print(" CURRENT_MOTOR_VALVE:");
  Serial.print(data.CURRENT_MOTOR_VALVE);
  Serial.print(',');
  Serial.print(" CURRENT_MOTOR_BALLAST:");
  Serial.print(data.CURRENT_MOTOR_BALLAST);
  Serial.print(',');
  Serial.print(" CURRENT_PAYLOAD:");
  Serial.print(data.CURRENT_PAYLOAD);
  Serial.print(',');
  Serial.print(" GPS_LAST:");
  Serial.print(data.GPS_LAST);
  Serial.print(',');
  Serial.print(" RB_LAST:");
  Serial.print(data.RB_LAST);
  Serial.print(',');
  Serial.print(" DATAFILE_LAST:");
  Serial.print(data.DATAFILE_LAST);
  Serial.print(',');
  Serial.print(" COMMS_LENGTH:");
  Serial.print(data.COMMS_LENGTH);
  Serial.print(",");
  Serial.print("\n\r");
  Serial.print("\n\r");
}
